### ISSUE TITLE
build fails OSX

### ISSUE THREAD

**Issue by tjstebbing** [beeven/node-openssl-verify-cert#2]
```
npm install node-openssl-verify-cert

> node-openssl-verify-cert@0.9.5 install /Users/pomke/code/identity-service/node_modules/node-openssl-verify-cert
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/addon/src/addon.o
  SOLINK(target) Release/addon.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/addon.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/pomke/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/Users/pomke/.nvm/versions/node/v6.6.0/bin/node" "/Users/pomke/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pomke/code/identity-service/node_modules/node-openssl-verify-cert
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/pomke/.nvm/versions/node/v6.6.0/bin/node" "/Users/pomke/.nvm/versions/node/v6.6.0/bin/npm" "install" "node-openssl-verify-cert"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! node-openssl-verify-cert@0.9.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-openssl-verify-cert@0.9.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-openssl-verify-cert package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-openssl-verify-cert
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-openssl-verify-cert
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pomke/code/identity-service/npm-debug.log
```

I have the latest node-gyp via:
`npm explore npm -g -- npm install node-gyp@latest`
and have brew installed openssl

**Comment by beeven** [comment]
It looks like Apple has depreciated OpenSSL as their default TLS library. Only installing OpenSSL via brew does not make the symbol links. 

You can try the following commands:

``` bash
brew update

brew install openssl

ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/

ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```

**Comment by SomeoneWeird** [comment]
Those symlinks don't seem to fix it. Even manually cloning the repo and modifying gyp file to include `/usr/local/opt/openssl/lib/` doesn't seem to fix it.

**Comment by beeven** [comment]
@SomeoneWeird I have `pkg-config`, `libtool` installed. Maybe this is how the linker find openssl? 

``` bash
$ pkg-config --libs openssl
-lssl -lcrypto -lz
```

I'm compiling on MacOS 10.12, and the build is successful on [travis-ci](https://travis-ci.org/beeven/node-openssl-verify-cert). My `node v6.7.0` was installed via brew.

**Comment by SomeoneWeird** [comment]
Unfortunately I have both those installed too! :(

```
➜  node-openssl-verify-cert git:(master) ✗ pkg-config --libs openssl
-lssl -lcrypto -lz
```

Same output.

Seems like TravisCI is only building on Linux, this only seems to affect macOS 10.12.

**Comment by beeven** [comment]
Actually Travis-CI builds on Linux and MacOS with Node v4 and v6. You can see build#13 has 4 instances.

**Comment by SomeoneWeird** [comment]
Ah true, sorry! Missed that. Any idea where we can go from here? This is a big showstopper :(

**Comment by beeven** [comment]
@SomeoneWeird I modified the binding.gyp (commit b75cfb2) to include /usr/local/opt/openssl/include and add /usr/local/opt/openssl/lib to the library. It can build correctly on my newly installed macOS 10.12 now. Is it working on yours?

Haven't published on npmjs.org yet. You may want to clone the code from github and try `npm install`.

**Comment by SomeoneWeird** [comment]
@beeven Seems it works! Had another colleague test to confirm, works for him too. Would be great if you could publish to npm asap - many thanks!
